Add initial sub-fragments support.
omnisci/omniscidb pull request #643
Opened 2021-04-05 13:39 UTC by ienkovich

Use sub-fragments for additional parallelism and better load balance. Works for aggregates only for now.

2021-05-12 19:29 UTC, ienkovich commented
> @ienkovich can you rebase the branch?

Done

2021-05-12 23:41 UTC, yoonminnam requested changes
The motivation and changes look good to me but I have few major comments:

1. I am not sure about the naming of this PR.
We use the term "fragmentation" to indicate a physical table representation, but this "subfragment" is just parallelizing per-fragment task, especially for group-by aggregation.
In this context, I'd like to recommend changing to "per-frag-parallelization" or similar.
(i.e., g_enable_subfragments --> g_enable_per_frag_parallel_groupby)

2. I've seen a noticeable regression in GPU query performance due to kernel launching overhead and seems not necessary to enable this parallelization for GPU due to the nature of GPU kernel execution. 
For instance, when I turned this on with `g_subfragment_size = 10000`, performing the following multi-aggregate query on 7M size table shows regression: ~20X times

1. Turn this on and execute query on GPU (1050ti 4GB)
omnisql> \gpu
omnisql> select flight_dayofmonth, avg(airtime), avg(depdelay), avg(carrierdelay), avg(lateaircraftdelay) from flights_2008_7M group by flight_dayofmonth;
flight_dayofmonth|EXPR$1|EXPR$2|EXPR$3|EXPR$4
1|104.2431117304259|11.05625866543425|16.34125512669251|22.17519710845179
...
31|105.922477685045|13.72178477690289|14.72826356974289|24.95929077133275
31 rows returned.
Execution time: 2585 ms, Total time: 2588 ms

2. Turn on this and execute the query on CPU
omnisql> \cpu
omnisql> select flight_dayofmonth, avg(airtime), avg(depdelay), avg(carrierdelay), avg(lateaircraftdelay) from flights_2008_7M group by flight_dayofmonth;
flight_dayofmonth|EXPR$1|EXPR$2|EXPR$3|EXPR$4
1|104.2431117304259|11.05625866543425|16.34125512669251|22.17519710845179
...
31|105.922477685045|13.72178477690289|14.72826356974289|24.95929077133275
31 rows returned.
Execution time: 123 ms, Total time: 126 ms

3. With the context of the above comment, I highly recommend you verify whether this does not cause regression when turning this on and show some numbers by performing in-house benchmarking that the workload or queries that you tried to tackle.

4. Can you check whether this PR passes ExecuteTest?
On my side, I got the following issue:
[ RUN      ] Select.FilterAndSimpleAggregation
2021-05-12T16:29:50.259702 F 3188583 1 Execute.cpp:908 Check failed: lhs.second.size() >= size_t(1) (0 >= 1)

2021-05-13 00:33 UTC, tmostak commented
> The motivation and changes look good to me but I have few major comments:
> 
> 1. I am not sure about the naming of this PR.
>    We use the term "fragmentation" to indicate a physical table representation, but this "subfragment" is just parallelizing per-fragment task, especially for group-by aggregation.
>    In this context, I'd like to recommend changing to "per-frag-parallelization" or similar.
>    (i.e., g_enable_subfragments --> g_enable_per_frag_parallel_groupby)
> 2. I've seen a noticeable regression in GPU query performance due to kernel launching overhead and seems not necessary to enable this parallelization for GPU due to the nature of GPU kernel execution.
>    For instance, when I turned this on with `g_subfragment_size = 10000`, performing the following multi-aggregate query on 7M size table shows regression: ~20X times
> 
> a) Turn this on and execute query on GPU (1050ti 4GB)
> 
> ```
> omnisql> \gpu
> omnisql> select flight_dayofmonth, avg(airtime), avg(depdelay), avg(carrierdelay), avg(lateaircraftdelay) from flights_2008_7M group by flight_dayofmonth;
> flight_dayofmonth|EXPR$1|EXPR$2|EXPR$3|EXPR$4
> 1|104.2431117304259|11.05625866543425|16.34125512669251|22.17519710845179
> ...
> 31|105.922477685045|13.72178477690289|14.72826356974289|24.95929077133275
> 31 rows returned.
> Execution time: 2585 ms, Total time: 2588 ms
> ```
> 
> b) Turn on this and execute the query on CPU
> 
> ```
> omnisql> \cpu
> omnisql> select flight_dayofmonth, avg(airtime), avg(depdelay), avg(carrierdelay), avg(lateaircraftdelay) from flights_2008_7M group by flight_dayofmonth;
> flight_dayofmonth|EXPR$1|EXPR$2|EXPR$3|EXPR$4
> 1|104.2431117304259|11.05625866543425|16.34125512669251|22.17519710845179
> ...
> 31|105.922477685045|13.72178477690289|14.72826356974289|24.95929077133275
> 31 rows returned.
> Execution time: 123 ms, Total time: 126 ms
> ```
> 
> 1. With the context of the above comment, I highly recommend you verify whether this does not cause regression when turning this on and show some numbers by performing in-house benchmarking that the workload or queries that you tried to tackle.
> 2. Can you check whether this PR passes ExecuteTest?
>    On my side, I got the following issue:
>    [ RUN      ] Select.FilterAndSimpleAggregation
>    2021-05-12T16:29:50.259702 F 3188583 1 Execute.cpp:908 Check failed: lhs.second.size() >= size_t(1) (0 >= 1)

@yoonminnam @ienkovich I realize I don't have all the context, but shouldn't we be looking at setting the sub-fragment size dynamically based on the number of devices available (could be gpus or cpu cores?). I.e. If i have 2 fragments of the default 32M rows, and have 8 CPU cores or 8 GPUs, I would ideally want the system to see I have 8 compute devices and make sub-fragments of 8M rows each, so i have a fragment per device (could argue for two for CPU for hyperthreading, but you get the idea). Is this feasible with the current approach?

2021-05-13 00:45 UTC, yoonminnam commented
@tmostak AFAIK we cannot support such dynamic chunk (or subfragment) allocation at this moment (in this PR I mean) since this assumes a chunk or resultset resides in a specific device (let say dev-0).
In this scenario, we only can split it into smaller and multiple chunks within the same device.

To support this, I think we manipulate the chunk fetching and task allocation scheme with the context of the dynamic sub-fragmentation, like:
GPU0: load the first chunk, process 1/4 part of the chunk
GPU1: load the first chunk, process 2/4 part of the chunk
GPU2: load the first chunk, process 3/4 part of the chunk
GPU3: load the first chunk, process 4/4 part of the chunk

GPU5: load the second chunk, process 1/4 part of the chunk
GPU6: load the second chunk, process 2/4 part of the chunk
GPU7: load the second chunk, process 3/4 part of the chunk
GPU8: load the second chunk, process 4/4 part of the chunk

A more advanced way is necessary to reduce chunk fetching costs.

2021-05-13 13:38 UTC, tmostak commented
@yoonminnam so just to clarify, the above is not an issue on CPU as we don't currently pin fragments to cores (or numa nodes)? If we were just to scope this for CPU, is there a way instead of specifying the target fragment size, to specify (or auto-detect based on # cores/hyperthreads) the number of target sub-fragments, perhaps subjected to a minimum sub-fragment size so that small datasets of say 1000 rows aren't being split up into tiny fragments?

2021-05-13 14:34 UTC, ienkovich commented
>    We use the term "fragmentation" to indicate a physical table representation, but this "subfragment" is just parallelizing per-fragment task, especially for group-by aggregation.
>    In this context, I'd like to recommend changing to "per-frag-parallelization" or similar.
>    (i.e., g_enable_subfragments --> g_enable_per_frag_parallel_groupby)

Sub-fragments are meant to make parallelization independent of a physical representation. The name was chosen due to the current implementation involving fragment split, but any other name would work for me. Our ultimate goal is to make parallelization independent from fragmentation for all types of queries. Group-by is the obvious first move because of the simplicity of the implementation. For other operations, we cannot predict the result size for each CPU core and therefore cannot pre-allocate required buffers. It can be solved but will require much more effort.

So, I'm OK with choosing another name, but probably something operation agnostic?

> 2. I've seen a noticeable regression in GPU query performance due to kernel launching overhead and seems not necessary to enable this parallelization for GPU due to the nature of GPU kernel execution.

This feature was designed with CPU in mind only. For CPU we have a problem with load balance. We can easily have  100+ cores on a server but in many cases we just don't have enough fragments to process. Even if a user chooses a fragment size to have a fragment per each core, it doesn't give us a nice balance load due to different core performance. We try to run many small tasks because it gives a good load balance and the overhead to run a task is quite small.

I don't know if this feature can be useful for GPU. I didn't even test this feature on GPU. IIUC for GPU we want to generate tasks of maximum size which can fit the device. It's quite different from what we want for CPU. My intention was to have this feature for CPU only.

> 1. With the context of the above comment, I highly recommend you verify whether this does not cause regression when turning this on and show some numbers by performing in-house benchmarking that the workload or queries that you tried to tackle.

There are cases when parallelization hurts performance. In these cases decreasing a fragment size causes performance losses. Sub-fragments enabling in such cases can reduce performance quite significantly. Performance losses are caused by high execution context initialization and reduction costs. With more fragments (or sub-fragments) we have more contexts to initialize and more result sets to reduce. There is another feature in #644 to address this issue by using a shared execution context.

Overall both these features are not ready to be enabled by default. We need more performance tests (we tried them on NYC Taxi and some of TPC-H queries only) and good heuristics to enable these features automatically.

> 2. Can you check whether this PR passes ExecuteTest?

All tests pass for me but my machine is not CUDA enabled. I should disable this feature for GPU.

2021-05-13 15:03 UTC, ienkovich commented
> I.e. If i have 2 fragments of the default 32M rows, and have 8 CPU cores or 8 GPUs, I would ideally want the system to see I have 8 compute devices and make sub-fragments of 8M rows each, so i have a fragment per device (could argue for two for CPU for hyperthreading, but you get the idea). Is this feasible with the current approach?

On CPU we don't want to generate a single task per core. Unfortunately, if we load all cores we cannot expect the same performance for all of them. In my experiments, I see the fastest core can easily be 2+ times faster than the slower one when we provide them with the same task (and all cores are utilized). To improve load balance we create small tasks and do not try to statically bind tasks to cores. This allows us to achieve load balance close to 100% but cores process different numbers of rows (that's why we don't try to apply this feature to non-aggregate operations - we cannot predict output buffer size for each core and pre-allocate it).

2021-05-13 17:34 UTC, yoonminnam commented
> @yoonminnam so just to clarify, the above is not an issue on CPU as we don't currently pin fragments to cores (or numa nodes)? If we were just to scope this for CPU, is there a way instead of specifying the target fragment size, to specify (or auto-detect based on # cores/hyperthreads) the number of target sub-fragments, perhaps subjected to a minimum sub-fragment size so that small datasets of say 1000 rows aren't being split up into tiny fragments?

@tmostak Yes, we can, but for covering arbitrary workload we need many more steps to go as @ienkovich described.

2021-05-13 17:38 UTC, yoonminnam commented
> > We use the term "fragmentation" to indicate a physical table representation, but this "subfragment" is just parallelizing per-fragment task, especially for group-by aggregation.
> > In this context, I'd like to recommend changing to "per-frag-parallelization" or similar.
> > (i.e., g_enable_subfragments --> g_enable_per_frag_parallel_groupby)
> 
> Sub-fragments are meant to make parallelization independent of a physical representation. The name was chosen due to the current implementation involving fragment split, but any other name would work for me. Our ultimate goal is to make parallelization independent from fragmentation for all types of queries. Group-by is the obvious first move because of the simplicity of the implementation. For other operations, we cannot predict the result size for each CPU core and therefore cannot pre-allocate required buffers. It can be solved but will require much more effort.
> 
> So, I'm OK with choosing another name, but probably something operation agnostic?
> 
> > 1. I've seen a noticeable regression in GPU query performance due to kernel launching overhead and seems not necessary to enable this parallelization for GPU due to the nature of GPU kernel execution.
> 
> This feature was designed with CPU in mind only. For CPU we have a problem with load balance. We can easily have 100+ cores on a server but in many cases we just don't have enough fragments to process. Even if a user chooses a fragment size to have a fragment per each core, it doesn't give us a nice balance load due to different core performance. We try to run many small tasks because it gives a good load balance and the overhead to run a task is quite small.
> 
> I don't know if this feature can be useful for GPU. I didn't even test this feature on GPU. IIUC for GPU we want to generate tasks of maximum size which can fit the device. It's quite different from what we want for CPU. My intention was to have this feature for CPU only.
> 
> > 1. With the context of the above comment, I highly recommend you verify whether this does not cause regression when turning this on and show some numbers by performing in-house benchmarking that the workload or queries that you tried to tackle.
> 
> There are cases when parallelization hurts performance. In these cases decreasing a fragment size causes performance losses. Sub-fragments enabling in such cases can reduce performance quite significantly. Performance losses are caused by high execution context initialization and reduction costs. With more fragments (or sub-fragments) we have more contexts to initialize and more result sets to reduce. There is another feature in #644 to address this issue by using a shared execution context.
> 
> Overall both these features are not ready to be enabled by default. We need more performance tests (we tried them on NYC Taxi and some of TPC-H queries only) and good heuristics to enable these features automatically.
> 
> > 1. Can you check whether this PR passes ExecuteTest?
> 
> All tests pass for me but my machine is not CUDA enabled. I should disable this feature for GPU.

@ienkovich okay, so let's make this only available on CPU for now.

2021-05-13 18:40 UTC, tmostak commented
Ok thanks @ienkovich and @yoonminnam, I now get the idea of small sub-frags for granular balancing, but I think until a thread can reuse a result set between "kernels"/frags/sub-frags, we will get hammered with any query with a non-trivial result set size. But still nice to land this and then we can start putting guardrails in/perhaps land some of the other thread pool/shared execution context stuff that should help with the above.

Btw, @yoonminnam this would probably be a good one to add a query hint for, both for dynamic profiling as well as selectively  turning it on where we know it will help. Is that easy as a follow-up?

2021-05-13 18:42 UTC, alexbaden commented
@tmostak take a look at https://github.com/omnisci/omniscidb/pull/644

2021-05-13 19:58 UTC, yoonminnam commented
> Ok thanks @ienkovich and @yoonminnam, I now get the idea of small sub-frags for granular balancing, but I think until a thread can reuse a result set between "kernels"/frags/sub-frags, we will get hammered with any query with a non-trivial result set size. But still nice to land this and then we can start putting guardrails in/perhaps land some of the other thread pool/shared execution context stuff that should help with the above.
> 
> Btw, @yoonminnam this would probably be a good one to add a query hint for, both for dynamic profiling as well as selectively turning it on where we know it will help. Is that easy as a follow-up?

@tmostak yes, I believe we can exploit our query hint framework to support those.

2021-05-13 21:25 UTC, ienkovich commented
> Ok thanks @ienkovich and @yoonminnam, I now get the idea of small sub-frags for granular balancing, but I think until a thread can reuse a result set between "kernels"/frags/sub-frags, we will get hammered with any query with a non-trivial result set size. But still nice to land this and then we can start putting guardrails in/perhaps land some of the other thread pool/shared execution context stuff that should help with the above.

The current implementation creates one execution context per thread in thread-local storage. Execution results are accumulated in these contexts and result sets are built only when all tasks are executed. So, we get a result set per core, not a result set per sub-fragment. 

#644 also introduces a feature to use a single shared execution context by all threads. In this case, we have a single result set for the whole execution step. It is useful when execution context initialization and/or result set reduction cost is very high. But building good heuristics to automatically choose an optimal execution context count will be a quite challenging task.

2021-05-17 13:45 UTC, ienkovich commented on QueryEngine/Execute.cpp
> +    ResultSetPtr* results,
With sub-fragments, we don't want to collect results at each method call. We want to accumulate results in a single buffer from multiple sub-fragments. In this case, I pass `nullptr` to indicate, that no result set should be produced.

2021-05-17 13:49 UTC, ienkovich commented on QueryEngine/ExecutionKernel.cpp
> +                       (!ra_exe_unit_.groupby_exprs.empty() || ra_exe_unit_.estimator);
Definitely will be added later.

2021-05-17 14:02 UTC, ienkovich commented on QueryEngine/ExecutionKernel.cpp
> +    for (size_t sub_start = start_rowid; sub_start < total_rows; sub_start += sub_size) {
This utility generates intervals to evenly divide a task between workers. Here we intentionally ignore the number of workers.

2021-05-17 14:40 UTC, ienkovich commented on QueryEngine/ExecutionKernel.h
> +      , num_rows_(num_rows)
OK

2021-05-17 14:42 UTC, ienkovich commented on QueryEngine/QueryExecutionContext.h
> +      const int64_t rows_to_process = -1);
OK

2021-05-17 15:00 UTC, ienkovich commented
>    In this context, I'd like to recommend changing to "per-frag-parallelization" or similar.
>    (i.e., g_enable_subfragments --> g_enable_per_frag_parallel_groupby)

What about `--enable-cpu-sub-tasks` and `--cpu-sub-task-size` or `--enable-cpu-autopar` and `--default-cpu-task-size`?

2021-05-17 15:55 UTC, yoonminnam commented
> > In this context, I'd like to recommend changing to "per-frag-parallelization" or similar.
> > (i.e., g_enable_subfragments --> g_enable_per_frag_parallel_groupby)
> 
> What about `--enable-cpu-sub-tasks` and `--cpu-sub-task-size` or `--enable-cpu-autopar` and `--default-cpu-task-size`?

The former pair seems suitable.

2021-05-17 15:57 UTC, yoonminnam commented on QueryEngine/ExecutionKernel.cpp
> +    for (size_t sub_start = start_rowid; sub_start < total_rows; sub_start += sub_size) {
Okay, since we control the granularity of the sub-task by user-given param, I think we can good to go.

2021-05-18 05:40 UTC, yoonminnam commented
LGTM

2021-05-18 16:02 UTC, yoonminnam commented
@ienkovich before merging this can you launch our test suites by performing tests by turning this feature on?
I assume you did a test without enabling this by default.

2021-05-18 19:00 UTC, ienkovich commented
@yoonminnam There are no regressions with the feature turned on by default and sub-task size set to 1.

2021-05-18 19:36 UTC, yoonminnam commented
@ienkovich in our internal test suite the following issue is found:

23:39:29 40: 2021-05-17T23:39:34.830848 F 35623 1 Execute.cpp:908 Check failed: lhs.second.size() >= size_t(1) (0 >= 1) 

So I want you to take a look at this and if possible can you figure out why this happens?

2021-05-18 22:11 UTC, ienkovich commented
@yoonminnam Unfortunately, I cannot reproduce this problem. Tried sub-task size set to 1 and 2. Is it in `Select.FilterAndSimpleAggregation` as you mentioned before?

Can you share some additional info (base branch, config options)?

2021-05-18 22:14 UTC, yoonminnam commented
@ienkovich Here is CMAKE build flag:

cmake -DCMAKE_C_FLAGS= -DCMAKE_CXX_FLAGS= -DENABLE_CUDA=OFF -DMAPD_EDITION=EE -DENABLE_RENDERING=OFF -DENABLE_PROFILER=OFF -DENABLE_ASAN=OFF -DENABLE_TSAN=OFF -DCMAKE_BUILD_TYPE=RELEASE -DPREFER_STATIC_LIBS=ON -DMAPD_IMMERSE_DOWNLOAD=ON -DMAPD_DOCS_DOWNLOAD=OFF -DTIME_LIMITED_BUILD=OFF -DTIME_LIMITED_NUMBER_OF_DAYS=38 -DMAPD_HOST_COMPILER= -DENABLE_LICENSING=OFF -DENABLE_LICENSING_AWS=OFF -DENABLE_FOLLY=ON -DENABLE_RENDER_TESTS=OFF -DMAPD_PACKAGE_FLAGS= ..

I manually turned relevant flags on based on your latest branch.

2021-05-19 10:51 UTC, ienkovich commented
@yoonminnam Tried your config and the following patch
```
--- a/QueryEngine/Execute.cpp
+++ b/QueryEngine/Execute.cpp
@@ -77,8 +77,8 @@
 bool g_enable_watchdog{false};
 bool g_enable_dynamic_watchdog{false};
 bool g_use_tbb_pool{false};
-bool g_enable_cpu_sub_tasks{false};
-size_t g_cpu_sub_task_size{500'000};
+bool g_enable_cpu_sub_tasks{true};
+size_t g_cpu_sub_task_size{2};
 bool g_enable_filter_function{true};
 unsigned g_dynamic_watchdog_time_limit{10000};
 bool g_allow_cpu_retry{true};
```
and still cannot reproduce the error. I noticed that this check is on another line in my branch than in your error message. Did you merge it with some other branch prior testing?

2021-05-19 18:14 UTC, yoonminnam commented
> @yoonminnam Tried your config and the following patch
> 
> ```
> --- a/QueryEngine/Execute.cpp
> +++ b/QueryEngine/Execute.cpp
> @@ -77,8 +77,8 @@
>  bool g_enable_watchdog{false};
>  bool g_enable_dynamic_watchdog{false};
>  bool g_use_tbb_pool{false};
> -bool g_enable_cpu_sub_tasks{false};
> -size_t g_cpu_sub_task_size{500'000};
> +bool g_enable_cpu_sub_tasks{true};
> +size_t g_cpu_sub_task_size{2};
>  bool g_enable_filter_function{true};
>  unsigned g_dynamic_watchdog_time_limit{10000};
>  bool g_allow_cpu_retry{true};
> ```
> 
> and still cannot reproduce the error. I noticed that this check is on another line in my branch than in your error message. Did you merge it with some other branch prior testing?

@ienkovich you need to enable `g_use_tbb_pool` to allow sub-fragment tasking.

2021-05-19 22:48 UTC, ienkovich commented
@yoonminnam You are right, I missed this one. Thanks!

The problem is in this statement:
```
  can_run_subkernels = can_run_subkernels &&
                       (!ra_exe_unit_.groupby_exprs.empty() || ra_exe_unit_.estimator);
```
It appears that for non-aggregate query
```
SELECT CAST(NULL AS BOOLEAN) AND val from table_bool_test WHERE id = 1;
```
this statement results in `true`. It happens because `ra_exe_unit_.groupby_exprs` is not empty, it holds `nullptr`. Is it a valid situation? Can you suggest a proper way to check for `groupby` query?

2021-05-20 03:03 UTC, yoonminnam commented
@ienkovich 

==
this statement results in true. It happens because ra_exe_unit_.groupby_exprs is not empty, it holds nullptr. Is it a valid situation?
==
If so, why don't you first check whether `ra_exe_unit_.groupby_exprs` has non_null ptr?
And please refer the following code that returns non-empty groupby_exprs list having a single nullptr as its content, see:

```
in RelAlgExecutor.cpp:
std::list<std::shared_ptr<Analyzer::Expr>> translate_groupby_exprs(
    const RelCompound* compound,
    const std::vector<std::shared_ptr<Analyzer::Expr>>& scalar_sources) {
  if (!compound->isAggregate()) {
    return {nullptr};
  }
  std::list<std::shared_ptr<Analyzer::Expr>> groupby_exprs;
  for (size_t group_idx = 0; group_idx < compound->getGroupByCount(); ++group_idx) {
    groupby_exprs.push_back(set_transient_dict(scalar_sources[group_idx]));
  }
  return groupby_exprs;
}

```
It seems a simple issue to fix, so let's make sure that a query having no groupby expression can pass through this code path.
As you already know, the issue is how can we allow this feature for a very specific type of query workload: a query having group-by aggregation.

==
Can you suggest a proper way to check for groupby query?
==
I suggest you check query type based on several query metadata you can use such as QueryDescriptionType, various query status stored in ra_exe_unit_ and so on

2021-05-20 14:55 UTC, alexbaden commented
To add to what @yoonminnam said, projection + group by queries use the same memory layout. We store a nullptr in the group by exprs vector as a cheap way to signal the memory layout. I think if you want to ensure you're a group by, just check for size > 1 or size == 1 and nullptr.

2021-05-24 22:56 UTC, ienkovich commented
> I think if you want to ensure you're a group by, just check for size > 1 or size == 1 and nullptr (which would tell you it's a projection).

Thanks! This works well. I fixed the issue in ExecuteTest but have some troubles when try to pass `HighCardinalityGroupByTest` with sub-task size set to 1. These tests don't execute SQL, they directly work with Executor feeding it with work units. All tests run groupby operations but set `is_agg` param to `false`. With sub-tasks it means we don't have reduction executed (input table has 2 rows). Is this `false` value intentional to avoid reduction or a bug?

2021-05-25 02:47 UTC, yoonminnam commented
> > I think if you want to ensure you're a group by, just check for size > 1 or size == 1 and nullptr (which would tell you it's a projection).
> 
> Thanks! This works well. I fixed the issue in ExecuteTest but have some troubles when try to pass `HighCardinalityGroupByTest` with sub-task size set to 1. These tests don't execute SQL, they directly work with Executor feeding it with work units. All tests run groupby operations but set `is_agg` param to `false`. With sub-tasks it means we don't have reduction executed (input table has 2 rows). Is this `false` value intentional to avoid reduction or a bug?

@ienkovich IIRC it is intentional since `is_agg` parameter only controls how we reduce resultset(s) and if it is set to false we just concat resultsets (without performing reduction).
But Is the branch passes the test if changing `is_agg` defined in the test to `true`?

2021-05-25 10:17 UTC, ienkovich commented
> @ienkovich IIRC it is intentional since `is_agg` parameter only controls how we reduce resultset(s) and if it is set to false we just concat resultsets (without performing reduction).
> But Is the branch passes the test if changing `is_agg` defined in the test to `true`?

@yoonminnam Original tests always produce a single result set and there is no difference whether we merge or concat. For sub-tasks results, I intentionally leave the sorting key empty to not get them concat (that helped to catch the issue with sub-tasks applied to non-groupby queries). Tests pass with sub-tasks if I set `is_agg` to `true`.

BTW there is also `LowerFunctionTest.LowercaseGroupBy` which fails because it checks for a particular row order in a result. With sub-tasks the order is random. The test can be fixed by adding `order by`.

Should I add these test adjustments to the branch?

2021-05-25 14:34 UTC, alexbaden commented
I think both those adjustments sound reasonable.

2021-05-25 17:32 UTC, ienkovich commented
@yoonminnam I pushed all fixes to pass tests with the feature enabled

2021-05-27 22:49 UTC, yoonminnam commented
@ienkovich One more test failure has been introduced when performing ExecuteTest with --enable-columnar-output option:

14:59:58 [ RUN      ] Select.MultiStepColumnarization
15:00:10 Expected equality of these values:
15:00:10   connector_.getNumRows()
15:00:10     Which is: 7
15:00:10   omnisci_results->rowCount()
15:00:10     Which is: 6

2021-05-29 00:40 UTC, yoonminnam commented
@ienkovich Also, I worried about the following OOM issue that occurred while performing our in-house CPU benchmarking:

2021-05-28T10:20:23.046291 E 73989 5 RelAlgExecutor.cpp:3243 Query execution failed with error ERR_OUT_OF_CPU_MEM: Not enough host memory to execute the query
2021-05-28T10:20:23.048792 E 73989 20 DBHandler.cpp:1430 Exception: ERR_OUT_OF_CPU_MEM: Not enough host memory to execute the query
2021-05-28T10:26:25.698966 E 73989 34 DBHandler.cpp:1430 Exception: Not enough CPU memory available to allocate 11341980688
2021-05-28T10:37:14.896165 F 73989 72 Calcite.cpp:595 Error occurred trying to communicate with Calcite server, the error was: 'socket open() error: Connection refused', omnisci_server restart will be required

Let say we execute two benchmarks M1 = {q11, q12, q3} and M2 = {q21, q22, q23, q24} and execute each query 15 times to get an average execution time.
And let us assume that we fail Q12 and Q23 due to OOM and if we restart the server and execute them separately we are okay.
So this indicates we may have an issue regarding memory cleanup... and so to land this we should analyze this thoroughly and fix this if necessary.

2021-05-31 11:52 UTC, ienkovich commented
> @ienkovich One more test failure has been introduced when performing ExecuteTest with --enable-columnar-output option:
> 
> 14:59:58 [ RUN ] Select.MultiStepColumnarization
> 15:00:10 Expected equality of these values:
> 15:00:10 connector_.getNumRows()
> 15:00:10 Which is: 7
> 15:00:10 omnisci_results->rowCount()
> 15:00:10 Which is: 6

`./ExecuteTest --enable-columnar-output=true` passes all tests for me on this branch (with sub-tasks enabled by default). Did you use some specific settings to get the error? I run tests with the following patch applied:

```
diff --git a/QueryEngine/Execute.cpp b/QueryEngine/Execute.cpp
index 8e50a33a72..bd2afdbae4 100644
--- a/QueryEngine/Execute.cpp
+++ b/QueryEngine/Execute.cpp
@@ -76,9 +76,9 @@

 bool g_enable_watchdog{false};
 bool g_enable_dynamic_watchdog{false};
-bool g_use_tbb_pool{false};
-bool g_enable_cpu_sub_tasks{false};
-size_t g_cpu_sub_task_size{500'000};
+bool g_use_tbb_pool{true};
+bool g_enable_cpu_sub_tasks{true};
+size_t g_cpu_sub_task_size{1};
 bool g_enable_filter_function{true};
 unsigned g_dynamic_watchdog_time_limit{10000};
 bool g_allow_cpu_retry{true};
```

2021-05-31 15:02 UTC, ienkovich commented
> So this indicates we may have an issue regarding memory cleanup... and so to land this we should analyze this thoroughly and fix this if necessary.

Sub-tasks usage can require more memory due to higher parallelism and therefore more execution contexts allocated. All additional structures for sub-tasks are held in existing context structures and use smart pointers. I don't see any leak risks here. Also, I don't see leaks when run ExecutionTest with ASAN enabled. You would probably see the same issue if use a small fragment size.

Some memory is probably stuck in pools and caches, so we can't get memory for additional execution contexts? You raise an interesting question of limiting parallelism on CPU to fit memory. Also, this might be a good case for the shared execution context feature.

2021-06-10 15:26 UTC, yoonminnam commented
@ienkovich Can you rebase this first?

And we still have the same two issues mentioned before: 

1. When setting subfragment_size = 2, I got random test failures like:
TSAN-failure: UpdateStorageTest.All_RHS_decimal_10_2_LHS_integer
ExecuteTest: Select.CountWithLimitAndOffset (centos7-cpu-x86_64)

Expected equality of these values:
  int64_t(size - 1)
    Which is: 655359
  v<int64_t>(run_simple_agg("SELECT count(*) FROM (SELECT rowid FROM " "count_test GROUP BY rowid OFFSET 1);", dt))
    Which is: 650807

Expected equality of these values:
  int64_t(size - 1)
    Which is: 655359
  v<int64_t>(run_simple_agg("SELECT count(*) FROM (SELECT rowid FROM " "count_test GROUP BY rowid OFFSET 1);", dt))
    Which is: 650807

ExecuteTest: Select.UnionAll --> Timeout

2. OOM while performing benchmarking

We perform benchmarking against multiple databases like TPCH, TPCDS, Twitter, Flight, and so on...
And I observed that there is a memory issue and so after some times later the memory consumption becomes almost 99%
 and so the test failure.
You may be able to reproduce this by executing several queries on various databases.

2021-06-18 11:17 UTC, ienkovich commented
> @ienkovich Can you rebase this first?

Done

> Issue 1. When setting subfragment_size = 2, I got random test failures like:

These random test failures can be reproduced on the master branch by enabling TBB. While TSAN issue is well known and we expect it to be fixed in TBB, other failures are new to me. I never saw them on Ubuntu but get them occasionally on CentOS. In my runs I see it happens only in tests which throw an exception in ExecutionKernel, so probably it's related to exception handling in TBB. This will require more investigation but is not related to this PR.

> **Issue 2. OOM while performing benchmarking**
> 
> We perform benchmarking against multiple databases like TPCH, TPCDS, Twitter, Flight, and so on...
> And I observed that there is a memory issue and so after some times later the memory consumption becomes almost 99%
> and so the test failure.
> You may be able to reproduce this by executing several queries on various databases.

I did the following test.
1. Upload TPC-H and NYX-Taxi data.
2. Run queries 1 time each
3. Check memory consumption 
4. Run queries 100 times each
5. Check memory consumption is the same as on step 3

I did it for sub-tasks enabled and disabled. Memory consumption on steps 3 and 5 doesn't depend on sub-tasks feature usage. Peak consumption on step 4 depends on sub-tasks though. E.g. for TPC-H Q11 we allocate twice more memory for execution. This is expected behavior, we pay the price for additional parallelizm. I suppose your machine is out-of-memory at some of such queries (which run OK after restart due to cleared caches). You can choose a bigger sub-task size to reduce memory footprint. BTW using a fragment size equal to sub-task size you use should produce the same memory consumption issues.

While increased memory consumption is expected, there are extreme cases when it also leads to performance losses. The first attempt to address this issue is already mentioned shared execution context feature. There will be more, I suppose.

2021-06-18 14:40 UTC, ienkovich commented
@yoonminnam #660 should resolve some issues with TBB

2021-06-24 07:01 UTC, yoonminnam commented
@ienkovich 
1. Okay, I checked the master with enabling TBB and saw some failures similar to what I found with this PR.
Let's first try to land #660 and then see what it can improve.

2. I changed the subfragment size from 0.5M to 50M, and now it passes all CPU benchmark queries.
But there is no performance improvement b/c I guess the size of the resultset seems not enough to fully exploit the benefit from this.
So I will try with more small size, i.e., 10M, but I guess it will show a similar trend as 50M case.
(Will share this with you if it shows meaningful improvement)

So now I wonder how can we determine the best sub-fragmentation size without incurring this OOM, and I know it is hard problem.

Let's think about this in a different way. If such extra memory consumption is unavoidable, then can we guard such OOM before entering query runtime? I know we may need very accurate result cardinality estimation to make sure about that but wonder if we can.

Also, I am thinking about only enabling this via our query hint framework.
That is, we can selectively apply this and also can control subfragment size as we want per-query manner.
From this approach, I think we can exploit this more safely, instead of trying to deploy this in all queries with the same fragment size where sometimes it can kill the backend without notice.
Thoughts?

2021-06-24 11:44 UTC, tmostak commented
@yoonminnam re your comment above, wouldn't any threshold above 32M have no effect with the default fragment size (32M rows)? If so, it seems definitely worth it to try a smaller fragment size (i.e. perhaps a few million rows)

Also the benefit (vs overhead) is likely to directly correlate to the computational heaviness of the query. It might be interesting to try this on heavier queries, for example perhaps involving geo (i know we can only do aggregates, but perhaps an avg of st_area or perimeter would be a good start (assuming this won't kick in if there's an aggregate on top of a join?).

2021-06-24 11:46 UTC, ienkovich commented
>    Let's first try to land [Fix race in TbbThreadPool. #660](https://github.com/omnisci/omniscidb/pull/660) and then see what it can improve.

Note that it will not fix TSAN issues which require fixes in TBB itself.

> 2. I changed the subfragment size from 0.5M to 50M, and now it passes all CPU benchmark queries.

Yeah, 50M is bigger that the default fragment size and therefore sub-fragments wouldn't give additional parallelization.

> So now I wonder how can we determine the best sub-fragmentation size without incurring this OOM, and I know it is hard problem.

We don't have to resolve all problems in this PR since it is an experimental feature disabled by default.

> Let's think about this in a different way. If such extra memory consumption is unavoidable, then can we guard such OOM before entering query runtime? I know we may need very accurate result cardinality estimation to make sure about that but wonder if we can do that based on some heuristics.

My ultimate goal was to control sub-task size and required memory independently. This PR is the first step to introduce sub-tasks. The next step is #644 which should be later extended to all groupby cases (currently, it is for keyless perfect hash table only). The idea was to then keep sub-task size quite small (say 100K rows) and control number of used execution contexts depending on its size. For small contexts we can create one per core, for huge ones we want to create just one shared and also allow to create any number of execution contexts (each shared by several cores with NUMA locality) to fit memory and find a balance between parallelization benefit and init/reduction costs. We will have to build some cost model and heuristics for that. It is never an easy part, so we will move step by step. For now it is not clear how much flexibility we have to have. Probably, one context per core and one context per system are two cases which would cover most cases, one context per NUMA node also looks reasonable. 

> 
> Also, I am thinking about only enabling this via our query hint framework.
> That is, we can selectively apply this and also can control subfragment size as we want per-query manner.
> From this approach, I think we can exploit this more safely, instead of trying to deploy this in all queries with the same fragment size where sometimes it can kill the backend without notice.
> Thoughts?

I like the idea. On early stages such hints might be a very useful testing tool. I hope we will not have to expose them to end users.

2021-06-24 12:00 UTC, tmostak commented
@yoonminnam If we are confident this has no performance impact off, I'd suggest we merge this before code rot sets in. If it's not too hard of a lift, per the above this is a great candidate for a query hint so that we can easily experiment with different sizes/query patterns.

2021-06-24 12:32 UTC, cdessanti commented
> for example, perhaps involving geo (i know we can only do aggregates, but perhaps an avg of st_area or perimeter would be a good start (assuming this won't kick in if there's an aggregate on top of a join?).

Also, filtering on plane coordinates using the real-time flight database we used to benchmarks the CPU edition on a big cluster, with a st_distance (or distance_in_meters) is the same.

2021-06-24 12:36 UTC, tmostak commented
@cdessanti what's the query?

2021-06-24 12:48 UTC, cdessanti commented
> 
> 
> @cdessanti, what's the query?

we could start with a perfect hash keyless like this one (we can change DIM with ST_DISTANCE, it shouldn't change so much) and then try with something more complicated (I have not idea about the maturity of this code)

select model,count(distinct icao) number_of_airplanes,count(*) number_of_contacts
from adsb_airplanes_test
where DISTANCE_IN_METERS(cast(-90.199402 as float), cast(38.627003 as float), Lon, Lat) < 20609.52215662825  
group by 1;

2021-08-16 22:11 UTC, closed without merging